# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

# [[main]]
#  name = "Methodology"
#  url = "#demo"
#  weight = 20

[[main]]
  name = "Weekly Stats"
  url = "#weeklystats"
  weight = 30


[[main]]
  name = "Evolution of COVID-19"
  url = "#timeline"
  weight = 40

[[main]]
  name = "Other Resources"
  url = "#other"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "PAP"
#    url = "https://osf.io/tdzr2/?view_only=1c507dd53b254c8d903821d580ff0c55"
#    weight = 70
